Providers Axios Retry Mechanism
Bitshala-Incubator/silent-pay-indexer pull request #20
Opened 2024-07-24 13:12 UTC by aruokhai

### Objective
It is paramount for a service that makes multiple Http calls such as Esplora Provider to have an Error Retry Mechanism, which is what is being rectified by this pull request

### Changes
- Implemented a custom  error retry logic for http calls  with exponential delay logic 
-  Modified  how  error logs are thrown During Http calls

### Scope Of Change 
Crittical , as it affects the fetching of data.

Solves #17

2024-08-12 17:49 UTC, theanmolsharma requested changes

2024-08-12 17:49 UTC, theanmolsharma commented on package.json
As discussed, please remove this dependency and implement custom retry logic

2024-08-12 17:49 UTC, theanmolsharma commented on src/configuration.model.ts
> +    @IsInt()
nit
```suggestion
    url: string;

    @IsInt()
```

2024-09-10 09:40 UTC, theanmolsharma requested changes

2024-09-10 09:40 UTC, theanmolsharma commented on src/common/request.ts
> +};
```suggestion
export const isNetworkError = (error): boolean => {
    return !(
        error.response ||
        !error.code ||
        ['ERR_CANCELED', 'ECONNABORTED'].includes(error.code)
    );
};
```

2024-09-11 09:31 UTC, aruokhai commented on src/common/request.ts
> +    const randomSum = delay * 0.2 * Math.random(); // 0-20% of the delay
It specifically is to add a little bit of jitter to make the calls less systematic which helps to avoids synchronised failures and distribute retries over time.  For example  If multiple request  attempt to retry a failed operation at the same exact time which is possible for esplora , they may all encounter the same underlying issue, leading to a cascading failure. Jitter introduces randomness into the retry timing, helping to spread out retries and reduce the likelihood of synchronized failures.

2024-09-12 12:24 UTC, theanmolsharma requested changes

2024-09-12 12:24 UTC, theanmolsharma commented on src/common/request.ts
> +    const delay = calculatedDelay;
```suggestion
    const delay = 2 ** retryNumber * retryConfig.delay;
```

2024-09-12 12:24 UTC, theanmolsharma commented on src/common/request.ts
> +    }
Axios can sometimes throw [AggregateError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError), we should also handle them here.
doing something like
```ts
        if (error instanceof AggregateError) {
            logger.error(
                `Aggregate Error encountered: ${error.message}`,
                error.stack,
            );
            for (const cause of error.errors) {
                logger.error(`Cause: ${cause.message}`, cause.stack);
            }
        }
```

2024-09-12 12:24 UTC, theanmolsharma commented on src/block-data-providers/esplora.provider.ts
> +    }
Instead of this, we should directly call `makeRequest` wherever `request` is called

2024-09-15 12:03 UTC, aruokhai commented on src/common/request.ts
> +    const delay = calculatedDelay;
Funny how i didn't catch this :smile:

2024-09-15 15:10 UTC, theanmolsharma commented on src/common/request.ts
> +    const delay = calculatedDelay;
nw dude, that's what reviews are for

2024-09-15 17:08 UTC, merged