Add Support for P2PKH and P2SH-P2WPKH Address Types
Bitshala-Incubator/silent-pay-indexer pull request #58
Opened 2024-11-15 09:36 UTC by notTanveer

This PR adds support for testing P2PKH and P2SH-P2WPKH address types in the indexer, ensuring silent blocks are correctly processed and retrieved for these transaction types. The test suite has been refactored improving maintainability and extending compatibility with diverse Bitcoin address types.

2024-11-18 07:04 UTC, aruokhai commented on e2e/helpers/wallet.helper.ts
> +        addressType: 'p2wpkh' | 'p2tr' | 'p2pkh' | 'p2sh-p2wpkh',
Kindly create a new type for this,  type AddressType = 'p2wpkh' | 'p2tr' | 'p2pkh' | 'p2sh-p2wpkh';

2024-11-18 07:09 UTC, aruokhai commented on e2e/indexer.e2e-spec.ts
> +        addressType: 'p2wpkh' | 'p2pkh' | 'p2sh-p2wpkh',
also replace the type

2024-11-18 07:14 UTC, aruokhai commented on e2e/indexer.e2e-spec.ts
> -    });
I would prefer it if the test function, in which i mean` it(`${addressType} - should ensure that the correct silent block is fetched`` is not enclosed in a normal function. It makes the code more readable.

2024-11-18 07:16 UTC, aruokhai commented on e2e/indexer.e2e-spec.ts
> +    testSilentBlock('p2pkh');
Also ensure to add _Pay-to-Taproot (P2TR)_ input as well.

2024-11-18 07:19 UTC, aruokhai commented on e2e/indexer.e2e-spec.ts
> +    ];
Also ensure to add Pay-to-Taproot (P2TR) input as well.

2024-11-18 07:20 UTC, aruokhai requested changes
Looks good, apart from some minor changes required.

2024-11-18 07:23 UTC, aruokhai commented on e2e/helpers/wallet.helper.ts
> +        type: 'p2wpkh' | 'p2tr' | 'p2pkh' | 'p2sh-p2wpkh',
same here

2024-11-19 10:36 UTC, theanmolsharma reviewed
Apart from removing hardcoded enum values for types, I don't have any other comments as of now.

2024-11-19 10:36 UTC, theanmolsharma commented on e2e/helpers/wallet.helper.ts
> +    addressType: 'p2wpkh' | 'p2tr' | 'p2pkh' | 'p2sh-p2wpkh';
please make an enum for this

2024-11-27 12:22 UTC, theanmolsharma requested changes

2024-11-27 12:22 UTC, theanmolsharma commented on e2e/helpers/wallet.helper.ts
> +import * as ecpair from 'ecpair';
```suggestion
import { ECPairFactory } from 'ecpair';
```

2024-11-27 12:22 UTC, theanmolsharma commented on e2e/helpers/wallet.helper.ts
> +    P2SH_P2WPKH = 'p2sh-p2wpkh',
```suggestion
    P2WPKH = 'P2WPKH',
    P2TR = 'P2TR',
    P2PKH = 'P2PKH',
    P2SH_P2WPKH = 'P2SH_P2WPKH',
```

2024-11-27 12:22 UTC, theanmolsharma commented on e2e/indexer.e2e-spec.ts
> +        it(`${addressType} - should ensure that the correct silent block is fetched`, async () => {
instead of this, the cleaner solution would be to `it.each()`

2024-12-13 13:27 UTC, closed without merging

2024-12-14 16:20 UTC, theanmolsharma commented
Why did you close this?

2024-12-14 16:32 UTC, notTanveer commented
> Why did you close this?

merge conflicts